### PR TITLE
Fix Ad blockers break search results and filtering #176

### PR DESCRIPTION
**Pull request by stuartlewis**
Would be fab if @sarahmonster could also test this, and thoughts from @brizee whether there is a neater way of doing this (rather than a dozen empty try/catches? Thanks :)

### CODE REVIEW

**Comment by brizee** [comment]
Should just be able to do one try catch in pushAnalytics in https://github.com/opentexts/opentexts/blob/main/public/scripts/analytics.js :smile:

**Comment by stuartlewis** [comment]
> Should just be able to do one try catch in pushAnalytics in https://github.com/opentexts/opentexts/blob/main/public/scripts/analytics.js 😄

Problem is (sorry, I forgot to put that in the issue!) that the ad blocker is blocking our analytics.js script, so anything which calls a function in there is failing. So the code isn't reaching as far as pushAnalytics as that script isn't loaded.

image

**Comment by sarahmonster** [comment]
I tested this locally and it works! The feedback tab still gets blocked (again, I suspect this is a classname issue that's probably unavoidable), but the search results show up as expected now. 🥳

**Review by sarahmonster — APPROVED** [review]
I tested this locally and it works! The feedback tab still gets blocked (again, I suspect this is a classname issue that's probably unavoidable), but the search results show up as expected now. 🥳

**Comment by brizee** [comment]
Oh... I wonder if just renaming that script would be enough - there is nothing particularly incriminating about the contents of the file so I imagine the ad blocker must just be blocking it by name.

**Comment by stuartlewis** [comment]
> Oh... I wonder if just renaming that script would be enough - there is nothing particularly incriminating about the contents of the file so I imagine the ad blocker must just be blocking it by name.

Good idea, and seems to work!  I'll just change the file name instead (event-recording.js doesn't get blocked) :) Thanks!

**Pull request closed without merging**
