### PR TITLE
feat: Add Docker support

### PR DESCRIPTION
**Pull request by tofumatt**
Used as a starter to allow @sarahmonster (and others) run the app via Docker. This is super-basic and not yet using Docker compose, but we should add that later 😄 

Opening this in case it's useful but I'll mark it as a draft for now.

-----

Once I run the app I get a 500, but I suspect that's related to my lack of Solr access:

Screenshot 2020-07-22 at 23 15 07

### CODE REVIEW

**Comment by stuartlewis** [comment]
Hi Matthew,

Thanks for adding the docker files - let me know when they're complete and I can merge the pull request.

If you can copy the env file to .env, and add 'CI_ENVIRONMENT = development' you'll see a more meaniningful error message.  However my guess would be the same as yours about solr access (especially if it takes 5secs for the error to load, as that's the timeout period). If you let me know the IP address / range, I can add it to the solr machine's firewall.

Thanks,


Stuart

**Comment by sarahmonster** [comment]
Thanks for your help with this, @tofumatt! I'm having a small-to-medium sized error with it when I try to run it:

image



According to @stuartlewis:

> The error [...] is CodeIgniter not being able to write to the cache directory.  [...]  If you make sure the /var/www/writeable/cache directory is writeable by your web server user, it should fix it (e.g. chmod 755, and maybe chown www-data:www-data or something similar will do the trick).

@tofumatt can you fix this in the Docker setup? I think that should make everything work properly. 🤞

**Comment by tofumatt** [comment]
Thanks for the heads-up! The writable directory is now writable and I tweaked the README instructions as well. Looks to be working now, showing the site. 👍 

Once @sarahmonster confirms it's all working with her IP address, I'll see about a docker-compose file to make running it nicer and then prep the PR for review.

**Comment by sarahmonster** [comment]
Update: it's working now! 🎉🥳🎊

Thanks for this, it should make things a whole bunch easier for me and for others as well! 💯

**Comment by tofumatt** [comment]
This is now ready for review. The README is sparsely updated to include docker commands. With Docker installed, easier route is running `docker-compose  --env-file /dev/null up` (required because the PHP CodeIgniter `.env` file lives in the root directory as well).

Then check out the app running at `localhost:8080`. 🎉

**Comment by stuartlewis** [comment]
Thanks Matt - works great! Much appreciated :)

**Pull request merged**
