### PR TITLE
feat: Show suggested searches on homepage

### LINKED ISSUE #85: Suggestion: should we show suggested searches on homepage?
I had this in my "list of things to file as issues eventually" so I thought I'd make a note of it now, although I'm not sure it's strictly required.

I like the simplicity of the current homepage, but we might want to consider adding suggested searches or similar, for users who maybe want to browse books available but aren't sure what to search for.

User testing & feedback will likely inform this to some degree, but it could be helpful to provide some suggested search terms, or ways of exploring the dataset if you're in more of a browsing mood than a searching mood, or you don't know explicitly what you're looking for.

### PR DESCRIPTION
**Pull request by sarahmonster**
This is still in progress, but here's an idea of how to present these in a visually appealing way:

Screenshot 2020-09-14 at 19 24 18

I'm thinking it might be nice if we had a selection of suggested searches, and cycled through them at random, showing three at a time—that way, you'd see different ideas each time you landed on the homepage, and we could build up a collection. (We could also show these elsewhere, like on the help page.)

The illustrations here are taken from the Noun Project and tweaked a little, but there's some discrepancy in style since they're done by different illustrators. They're a little awkward looking as a result, but I wanted to get the idea across first. 

If this feels like a good direction, I'd suggest we actually use a custom illustration set here, so that the illustrations work well together and form a cohesive set. That will be a little time-consuming, but we can start with a set of three and then build out more as time permits.

@stuartlewis I'd love your thoughts here! (Also, I'm not sure about the "Try these searches" heading, or if we need a heading at all...)

Close #85.

### CODE REVIEW

**Comment by stuartlewis** [comment]
Looks great! We could add all these in a config file and randomly choose three each time?

I wonder if a heading is probably needed, to give a hint about what they are?

**Comment by sarahmonster** [comment]
I played around with style a bit, and here's where I got to:

Screenshot 2020-09-21 at 23 48 53

These could all be refined a bit—they're not quite 100% yet—but so long as this direction feels right, I think we can merge this in & tweak iteratively as time allows.

**Comment by stuartlewis** [comment]
Brilliant - looks good!  I think this will really help the home page in terms of drawing people in by showing them the sort of things they can do.

**Comment by sarahmonster** [comment]
Yay! I'll probably refine these a wee bit pre-launch, and then we can add more (and randomise the suggestions!) as time allows—I'll file a follow-up issue for that.

**Pull request merged**
