### PR TITLE
Logo Animation Prototypes

### PR DESCRIPTION
**Pull request by brizee**
Just for fun I thought I'd take a look at what could be done for #83 - the script for it is horrible but it shows off two different ways of animating. One keyframing the individual points which is a bit more complex but gives a lot of freedom and the other mapping them to a circle and then manipulating the circle which is a bit simpler but might be fine if that's all we intend to do.

They're both quite over the top but just to show what we could do this way :smile:

One is bound to hovering over the logo
opentexts_logo_hover

and the other to loading content (i.e. changing filters)
opentexts_logo_spinner

### CODE REVIEW

**Review by stuartlewis — COMMENTED** [review]
I'm no designer, but I quite like both (they serve different purposes). 

It makes me imaginge an easter egg: search for 'london' and the hover version will change to the London Eye, search for 'shakespear' and the points/lines will make the bard's face, etc! :D

**Comment by sarahmonster** [comment]
I _am_ a designer 😉 and I love, love, love these! I'll test them out later and provide more detailed feedback, but just wanted to drop in to say they look absolutely lovely. 😍

**Comment by brizee** [comment]
Aw thanks :smile: I was worried something quite exaggerated like this might dilute the brand but happy to defer to you guys and glad you like them. They are definitely a bit rough around the edges there is some snapping between the circle based model and the point based one but should be able to polish this all up depending on how we decide to proceed.

**Review by sarahmonster — CHANGES_REQUESTED** [review]
I _finally_ got around to pulling this PR down and testing it out, and my feedback is much the same: I love these _so much_. Seriously, great work—this is the exact kind of thing I had in mind here, except that I would have tried to do it with CSS animations and it would have taken me a million years. 

I actually have very little critical feedback at all here, which is super unusual for me. Two very minor items:

- I might try to aim to keep the centre dot static at all times, and have the other nodes animate around it. This would help to ground the animations and give them a shared root, even when other elements are changing.
- There's a little bit of a stutter (for lack of a better word) at the tail end of the circle/loading animation, when the nodes snap back into place. I suspect you're already aware of this though!
- We should definitely include the hover animation on the homepage as well, so I suspect we'll need to make the logo into a reusable component. (I'm also adding the logo to the footer in #128, but we may or may not want to add the animation there as well, depending on performance ... stuff.)

I worked really hard to come up with more critical feedback, but that's all I've got here. I'd love to see these incorporated into the site—they're absolutely lovely! ❤️

I'm marking this as "request changes" for the above, but if any of it proves thumpingly difficult, I'm happy with merging what we have—it's a big improvement and we can always handle things iteratively as needed. 

Let me know how/if I can help here! 🙂

**Comment by brizee** [comment]
Think that's this one taken care of 😄 I had to do a different approach to alt texts for accessibility on canvases - pretty sure I have it right but worth double checking.

**Review by stuartlewis — APPROVED** [review]
Seems to be working well for me, thanks! [https://design.opentexts.world/](https://design.opentexts.world/) is running this code now for testing.

**Review by sarahmonster — APPROVED** [review]

**Comment by sarahmonster** [comment]
These look lovely! 😍 Excellent work. I vote we merge them in.

**Comment by brizee** [comment]
Great :smile: I consider this a riskier/less valuable changeset than #179 so I intend to wait til that one is merged - if something is notably wrong it'll be easier to revert this changelist this way.

**Comment by stuartlewis** [comment]
Hi @brizee - I've just merged the tailwind cleanup, and this PR will still merge cleanly, so shall we go for it?! Then I can deploy tonight, ready for launch tomorrow :) 🚀

**Comment by brizee** [comment]
Lets do it :smile:

**Pull request merged**
