### PR TITLE
chore: Tailwind cleanup

### LINKED ISSUE #163: Tailwind cleanup
From Slack...

https://tailwindcss.com/docs/controlling-file-size seems to be the ticket

### PR DESCRIPTION
**Pull request by sarahmonster**
This PR does three things:

- Opts us into Tailwind's breaking changes early. This ensures an easy upgrade process when the time comes and may help reduce file size as well.
- Purges unused CSS. This takes our CSS from to 1.43 MiB to 35.3 KiB, which seems like a good delta if a MiB is effectively equal to a MB, which I think it is. I think my local runs the development CSS (non-purged) so I'm not sure how best to check if this has caused any snafus—maybe just wait until the change is on the staging site and check there?
- Attempts to split the CSS files into multiple smaller files. This would theoretically make it easier to manage the CSS but I'm struggling with finding a path that webpack is able to process—I just get errors with everything I try. 😭 @brizee might you be able to help with the build side of things here?

Oh, and it also fixes an issue with the path that was making the sharing image not show up, so that should be better too. File paths are basically my forever Achilles' heel. 🦶

Fix #163.

### CODE REVIEW

**Comment by brizee** [comment]
I'll take a look at this a little later :smile:
also MiB is possibly closer to your interpretation of MB than MB is :grin:
MiB is a Mebibyte 1024 KiB's make a MiB and each KiB is 1024 bytes - MB has been redefined as 1000 KB each of 1000 bytes.

Adoption of MiB isn't universal so MB is often used interchangeably.

**Comment by stuartlewis** [comment]
What do we think about checking-in the compiled CSS? This would make deployment everso slightly easier (but not a showstopper at all).

**Comment by stuartlewis** [comment]
What do we think about checking-in the compiled CSS? This would make deployment everso slightly easier (but not a showstopper at all).

**Comment by sarahmonster** [comment]
Typically I'm not a huge fan of checking in compiled CSS, mostly because it can often lead to merge conflicts. As a result it's often better to have the compilation as part of the build/deployment process, but ideally this would be automated. 

I'm easy either way though—I already do a lot of client work that uses a system of checking in built files, so I'm pretty comfortable dealing with the resulting merge conflicts.

**Comment by stuartlewis** [comment]
No problem.  Having to run an 'npm install; npm run build' isn't a a big problem for deployment
.

**Comment by brizee** [comment]
Fixed the build step for this - turns out for some reason the postcss-loader doesn't like extensions other than .css so initially went that way then realised that postcss has an import plugin of its own which seems more how this is meant to be done so swapped to that one, I also:
* added js files for the purge operation as some classes may just be mentioned there. 
* re-ordered the imports so that all custom css was after all tailwind css as `main-container` was being overridden by `container` and the width wasn't right
* turned on purging by default - admittedly I'd meant to turn this back off but also intended to discuss with you guys. The purge operation feels kinda dangerous (prone to breakage if left unobserved) so I'm minded to leave purge on all the time so we're always debugging the results?

File size is 35.6KiB atm - would be tempted to further run this through minification - also what do we think about doing the same thing with the JS?

**Comment by brizee** [comment]
Update: done the minimisation as well to get us down another third or so :smile: lots of room even before serverside compression.

**Comment by sarahmonster** [comment]
> turned on purging by default - admittedly I'd meant to turn this back off but also intended to discuss with you guys. The purge operation feels kinda dangerous (prone to breakage if left unobserved) so I'm minded to leave purge on all the time so we're always debugging the results?

Absolutely agree. Does this mean that when I'm working on it locally, I'm testing the "purged" CSS? That makes sense to me—my biggest concern here was that there might be some classes that got missed, and it was hard to test beyond compiling and pushing to the staging site. Sounds like this resolves that issue though, yay!

Thanks for fixing up the paths. I'm just going to fix the merge conflict, and then I think this is ready to merge?

**Comment by brizee** [comment]
> Does this mean that when I'm working on it locally, I'm testing the "purged" CSS?

Exactly :smile: Any time the app.css is generated it'll be a purged one. It will only be minified in production (though I suspect we all use browser debugging tools rather than looking at the raw css anyway)

**Review by stuartlewis — APPROVED** [review]
Seems to work well.  With server-side compression, is now at 5.2KiB. Running on [https://design.opentexts.world/](https://design.opentexts.world/)

**Comment by brizee** [comment]
> 
> 
> Seems to work well. With server-side compression, is now at 5.2KiB. Running on https://design.opentexts.world/

Did you deploy correctly? design.opentexts.world seems to be attempting to load livereload and such from localhost now?

**Comment by stuartlewis** [comment]
> > Seems to work well. With server-side compression, is now at 5.2KiB. Running on https://design.opentexts.world/
> 
> Did you deploy correctly? design.opentexts.world seems to be attempting to load livereload and such from localhost now?

Whoops, sorry!  Deploying it overwrote my prod solr server settings, so I changed the .env to dev so I could see what was going on, and forgot to change it back. Fixed now! Thanks for spotting.

**Comment by brizee** [comment]
No worries :) Glad it wasn't something I'd changed.

**Pull request merged**
