### PR TITLE
feat: Apply initial brand to site 🎉

### PR DESCRIPTION
**Pull request by sarahmonster**
This PR applies our initial branding. It's still quite rough, and lots of bits & pieces aren't there yet, but it's a pretty major restructuring of things, both from a visual and a code point of view, so it's probably now in a good place to review and merge in, if not necessarily to push to the live site (I'm guessing that deployments are manual, although I'm not sure). 

Note: I don't have write access to the repo so I'm doing this as a feature branch from a fork on my own repo, but if you feel comfortable granting me write access, it's a bit more of a straightforward process to create smaller feature branches against the repository. (A good approach is to [protect the main branch](https://docs.github.com/en/github/administering-a-repository/about-protected-branches) from unapproved pull requests!) Anyway! Either approach works, I'd just totally forgotten how to make a fork in the first place. 😜

This is, as mentioned, something of a colossal PR, but they'll be smaller and more iterative in the future. Code-wise, I've broken a lot of the larger files up into much smaller pieces so they're easier to manager, more reusable, and so there's less code repetition. We could probably manage to remove more code still, but let's see how we get on with this.

@tofumatt want to take a look at the README to make sure I'm not talking nonsense with respect to the Docker config? 

Here are a few screenshots to show what it looks like on my end:

image

image

image

I'll file GitHub issues for remaining tasks, but here's a few highlights before I forget:

- [ ]  add search icon/button to search input
- [ ]  improve copy & design for all static pages
- [ ]  hover & focus states for interactive elements
- [ ]  implement Tailwind classes for all reused component classes
- [ ]  add selected states to navigation menu
- [ ]  responsive styling & alignments
- [ ]  audit colour usage & optimise
- [ ]  "more results" button needs to hooked up to more results
- [ ]  normalise author & publication data where possible
- [ ]  modal menu needs to be built out
- [ ]  filters need to be built out & hooked up
- [ ]  types should be added back in
- [ ]  Doorbell needs styling
- [ ]  accessibility review
- [ ]  add a favicon & social sharing images
- [ ]  autocomplete drop-down needs styling
- [ ]  animate logo on hover
- [ ]  add subtle background effect
- [ ]  consider suggested searches on homepage
- [ ]  icons for file types → can we make these clearer? alt text?
- [ ]  show current result set in [x-100] of 602 results.
- [ ]  footer text?
- [ ] use of `file_get_contents()` for svgs doesn't seem to work properly in CodeIgniter?
- [ ] style no results found page

### CODE REVIEW

**Comment by stuartlewis** [comment]
Thanks! :)

I'll setup a new test subdomain so we can try this on the production server.

**Comment by stuartlewis** [comment]
Running live! https://design.opentexts.world/

**Comment by sarahmonster** [comment]
Lovely! Thanks, @stuartlewis! I'll work on filing that pile of follow-up issues before I forget what they all mean. 😉

**Comment by sarahmonster** [comment]
@stuartlewis would you be able to add @brizee to this repo as well? He'll be working on some issues with us. (You'll probably also get an email shortly with his IP address for the solr firewall!)

**Comment by stuartlewis** [comment]
Thanks @sarahmonster . I've now added @brizee to the repo too.

**Pull request merged**
