### PR TITLE
feat: Filter view

### LINKED ISSUE #13: Display filters in popover menus
Instead of showing filters in a sidebar, where they can get a little long and hard to scroll, let's collapse them into expandable flyout/popover/dropdown/whatever menus, search engine style. This way, users who need to use the filters will have easy access to the relevant filters, but users who just want to get right into the results don't need to bother with them at all.

language-filter

Other notes:

- When/if we have more filter groups than the five shown here, we’ll want to hide the least useful ones under a “More…” mechanism. (See earlier mockups, but we can deal with this later as/when we add filters.)
- Can we make filters contextual, depending on the dataset returned? (Maybe as a v2)
- Would it help to show number of results for each filter, or does that just add extra noise?
- When a list of filters has more than 10 options, we should provide a search and attempt to show the most relevant or useful filters in a separate section at the top of the page (see #9)

### PR DESCRIPTION
**Pull request by sarahmonster**
This is the first pass at adding filters back to the site, using a pop-over approach as per mockups. 

Close #13.

@brizee I'm making a draft PR here so it's easier to collaborate & discuss—I'll be adding some commits to your branch to pretty things up a wee bit.

### CODE REVIEW

**Comment by sarahmonster** [comment]
I've updated this to merge in changes from the main branch, but I'm still seeing an error:

Screenshot 2020-08-17 at 11 31 02

(I get the same issue with the Language facet—if I comment out both lines, everything works fine, but the filters don't appear.)

Is there a step I've missed? 🙂

**Comment by brizee** [comment]
> I've updated this to merge in changes from the main branch, but I'm still seeing an error:
> 
> Screenshot 2020-08-17 at 11 31 02
> 
> (I get the same issue with the Language facet—if I comment out both lines, everything works fine, but the filters don't appear.)
> 
> Is there a step I've missed? 🙂

Frustratingly I don't see this issue locally but the commit I pushed should fix it regardless.

**Comment by sarahmonster** [comment]
That seems to have done the trick—thank you! 🎉



I've pushed a few initial style changes, but there are a few things I may need some help with:

- [ ] The "All [x]" option should always be visible at the top of the list, so users know what they have currently selected. (There should always be something in the list with a check mark—this provides an affordance that demonstrates how the filters work, essentially.)

- [ ] I've added the counts back in per feedback here—it sounds like it's going to be helpful to show them, so let's try that now and see how it works. There looks to be some unexpected spacing appearing after the un-selected filter text:

Screenshot 2020-08-17 at 14 39 06

In this screenshot, the selected filters look right (I've added padding via CSS classes) but the unselected ones seem to have an extra space. Is there possibly some whitespace being output?

- [ ] I'm not quite sure how to navigate the filters using only a keyboard. I can open the filter, but I'm not sure how to navigate into the filter and select/deselect filters. I suspect this is because (in part) we're using `<li>` elements here, rather than `<a>`. I'm going to push a change that uses a tags instead, which should help make things a bit more accessible, as well as giving us hover and focus styling, but it'll need a bit more work to make it accessible to keyboard users. 

Label behaviour:
- [ ] **Default/all:** When "All [x]" is selected, the label for the popover should read "All [x]". (For example, right now the default says "Library" but it should say "All libraries" to reflect the currently-selected filter.) Example: _All libraries_
- [ ] **Single filter:** When a single filter is selected, the label should display that filter. Example: _Internet Archive Books_. It currently does this, except there's some weirdness with commas:
Screenshot 2020-08-17 at 14 56 27

- [ ] **Multiple filters:** When multiple filters are selected, the label should say "Multiple [x]s". This prevents the label from getting too long & hard to read.  Example: _Multiple libraries_

Screenshot 2020-08-17 at 14 58 45

**Comment by stuartlewis** [comment]
Looks like the additional comma is coming from: https://github.com/opentexts/opentexts/blob/feature/filter-view/app/Views/templates/filter-generic.php#L11

It can be fixed by stripping the leading two characters:

<span class="text-gray-700 focus:text-blue-700"><?= $currentValue != null ? substr(join(", ", $values),2) : $label; ?></span>

**Comment by brizee** [comment]
> Looks like the additional comma is coming from: https://github.com/opentexts/opentexts/blob/feature/filter-view/app/Views/templates/filter-generic.php#L11
> 
> It can be fixed by stripping the leading two characters:
> 
> ```
> <span class="text-gray-700 focus:text-blue-700"><?= $currentValue != null ? substr(join(", ", $values),2) : $label; ?></span>
> ```

Don't think we should just trim this, the join behaviour shouldn't have that as a suffix - it suggests there might be additional zero length entry in the value `$values` array to me?

**Comment by stuartlewis** [comment]
Yes - you're right! (I wasn't aware of the PHP join function - I just know it as implode).

It looks like the extra character (a pipe/$7C) is getting added in the javascript that adds a filter value and submits the form.  

Test: Load results, select a filter value, and see the URL: e.g. https:/design.opentexts.world/search?q=&organisation=%7CWellcome+Collection&language=

If you manually remove the %7C it works as expected, and extra filters can be added successfully.

I'll take a look at the javascript now...

**Comment by stuartlewis** [comment]
The issue is that in the javascript below (adding a new item to the filter list), running a 'split' on an empty string returns an array of one (empty) string, rather than a zero length array.

This can be addressed as follows... in Views/templates/filter-script.php

```javascript
function addValue(element, value)
    {
        var values = element.value.split("|");
        if (element.value === "") {
                values = [];
        }
        for(var i = 0; i < values.length; i++)
        {
            if(values[i] === value)
            {
                return;
            }
        }
        values.push(value);
        element.value = values.join("|");
        element.closest('form').submit();
    }

**Comment by brizee** [comment]
Looks like a good fix 😄 and yeah the PHP implode/explode funcs always get me for some reason, can always remember explode but implode gets replaced as most other languages I work with are split/join.

**Comment by brizee** [comment]
Aside from that I've addressed all but the accessibility aspect which is a bit of a pain - the main problem will be that if any of the filters is focused by keyboard manipulation the popup will close so will probably just have to change approach there. :smile:

**Comment by brizee** [comment]
> Don't think we should just trim this, the join behaviour shouldn't have that as a suffix - it suggests there might be additional zero length entry in the value `$values` array to me?

Wow kudos for deciphering this, you can tell I had _just_ finished work.

**Comment by sarahmonster** [comment]
It sounds like the last thing we need to deal with here is making the filters accessible to keyboard users, is that right? I definitely think this is important to make sure we have functioning from the outset, especially if it will require structural changes to how the filters are built out. Let me know how I can be of help here. 🙂

I tried to pull the latest changes for testing and seem to be getting an error again:
Screenshot 2020-08-24 at 13 42 15

Clearly I am very skilled at finding bugs! 😉

**Comment by brizee** [comment]
> It sounds like the last thing we need to deal with here is making the filters accessible to keyboard users, is that right?

The only other thing is the Apply button/async loading of data - I'm keen to just address both in Javascript at this point as an extension of #73 so I'd push for merging this for now. Extending javascript to filters will be my next piece of work in any case.

**Comment by sarahmonster** [comment]
That makes sense to me! I just want to be sure we're not making accessibility an afterthought. 🙂 I'm happy to file it as a follow-on issue, especially if it's easier to tackle once some more structural pieces are sorted out. 

I'm going to mark this PR as ready for review and I think we can merge once we sort out the bug in `filter-generic.php`.

**Comment by brizee** [comment]
Sounds good, fixed the bug there and also included @stuartlewis's fix outlined above as he'd not pushed (I think just some confusion over who was going to do it? :smile:)

**Comment by sarahmonster** [comment]
Yay! I glommed onto your branch and moved the check marks to the left, which I think works better here for legibility, especially with the counts included in the filters. If that seems good, I think this is ready to merge now, so long as we make sure to handle the accessibility side of things next. 👍

**Comment by sarahmonster** [comment]
That sounds great by me! I'm going to merge this & file a follow-up issue to be sure it's on our radar. 🙂

**Pull request merged**
