### PR TITLE
Javascript Rendering

### LINKED ISSUE #58: Display the current number of result set
The [x-100] here is a placeholder. We should replace it with an actual value that's representative of the actual results being shown, so that users can tell where they are in the results being returned.

Screenshot 2020-08-10 at 13 11 14

This will work in concert with the "more results" button.

### LINKED ISSUE #59: "More results" button needs to hooked up to more results
To simplify the user experience, I've removed the navigation in favour of a single "more results" button. (The rationale being that, in searching, you very rarely want to navigate through pages of less relevant search results.... you just want to load more until you find whatever it is you want, so we really just need a button that accomodates that single behaviour.)

Screenshot 2020-08-10 at 13 11 14

So! We've got the button, we just need to hook it up.

Probably worth addressing in concert with #58, which shows the number of the currently-displayed result set.

### PR DESCRIPTION
**Pull request by brizee**
Gonna bring this into a PR now for finalization - more work will be needed to adapt the filters to the javascript model but I want to wait til the work in #72 is merged before tackling that to avoid conflicts.

closes #59 
closes #58

### CODE REVIEW

**Comment by stuartlewis** [comment]
Fab, thanks for this @brizee! I'll get the staging site updated on an hour or so.

**Comment by brizee** [comment]
Great thanks @stuartlewis - this tackles a whole bunch of our remaining beta issues so good to get it in place :smile:

**Comment by stuartlewis** [comment]
The load more results button doesn't seem to be working on the [staging site](https://design.opentexts.world/search?q=cheese)...

image

Any immediate ideas? Or I can start debugging.

**Comment by brizee** [comment]
No immediate fixes - looks like the problem is the data endpoint on the PHP side: 
image

**Comment by brizee** [comment]
Oh... I see it 🤦‍♀️

**Comment by brizee** [comment]
See #92

**Comment by stuartlewis** [comment]
Works great now - thanks.  We probably also need to look at the loading button, and when to remove / hide / not show it.  E.g. do a search cheesecake, there's only 10 results, so the button isn't needed if current results >= number of results.

image

**Comment by brizee** [comment]
Ah yeah - I addressed that in my non-javascript solution but forgot about it when adding async loading - I'll raise an issue for it.

**Pull request merged**
