### PR TITLE
Javascript Filters

### LINKED ISSUE #75: Ensure filters are accessible to keyboard users
Right now, the filters are impossible to use if you're using a keyboard only—we'll want these to be fully accessible to keyboard users, obviously! 

I'm attaching this to the Beta milestone since I do think it's pretty vital to the overall functionality of the site, but it's possible that none of our testers would be using keyboards to navigate the site, so if needed we can probably scoot this over to the "Polish" milestone if it's going to be hairy to sort out.

See #72 for further discussion.

### PR DESCRIPTION
**Pull request by brizee**
This is a bit of a Bulky PR, this introduces:
* Asynchronous loading for filter changes and all associated visual changes (counts updating, available filters changing)
* History API to ensure URL remains valid as filters change
* Skeleton Loading UI (as discussed with @sarahmonster) for visual state when replacing full content

opentexts_async_filter
opentexts_async_filter_options

closes #75

### CODE REVIEW

**Comment by brizee** [comment]
Added a quick focus and hover state to the filter buttons to mimic #108 as this was the only element with no focused state which blocked closing #75

opentexts_filter_focus

closes #75

**Comment by stuartlewis** [comment]
Wow - brilliant work, thanks! I have switched the [staging site](https://design.opentexts.world/) to this branch for testing.

It looks great and seems to work well.  The only issue seems to be that the button to load further results doesn't work anymore (although not seeing any javascript errors i nthe console, and the next ten results are bring pulled from the server.

**Comment by brizee** [comment]
Interesting - I'll take a look - I did restructure the response a little to get the additional filter data down.

**Comment by brizee** [comment]
That should be it :) I was binding fetchMoreResults directly to the click event on the More Results button - when I added a parameter the click event would send a MouseEvent as the first param which is truthy and so would be treated as full replace.... gotta love javascript sometimes.

**Comment by stuartlewis** [comment]
Thanks - seems to be working nicely! Site updated again.

I'm happy for this to be merged if you are?

**Review by stuartlewis — APPROVED** [review]

**Comment by brizee** [comment]
I'd like to give @sarahmonster a bit of time in case she has a chance to check the gifs and confirm she's happy with the Skeleton Loading, we discussed it briefly then I went off and did it but if she's too busy travelling to come back to us then we can merge it fine :smile:

**Comment by brizee** [comment]
Doesn't look like Sarah's gonna have time so lets get this merged :smile:

**Pull request merged**
